# Generated by Django 5.2.8 on 2025-11-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('id',)},
        ),
    ]
