# Generated by Django 5.2.8 on 2025-11-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizzamodel_name_alter_pizzamodel_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzamodel',
            options={'ordering': ('id',)},
        ),
    ]
